version: '3'

services:
  api:
    build: .
    container_name: avaliacao_api
    working_dir: /var/www
    depends_on:
      - mysql
    volumes:
      - .:/var/www
    ports:
      - "3008:80"
    network_mode: avaliacao

  mysql:
    image: mysql:5.6
    container_name: avaliacao_db
    volumes:
      - mysqldbvolume:/var/lib/mysql
    ports:
      - "3316:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=avaliacao
      - MYSQL_DATABASE=avaliacao
      - MYSQL_USER=avaliacao
      - MYSQL_PASSWORD=avaliacao
    network_mode: avaliacao

networks:
  avaliacao:
    external: true

volumes:
  mysqldbvolume:
    driver: local