# For more information: https://laravel.com/docs/sail
version: "3"
services:
  api:
    container_name: ${DOCKER_CONTAINER}-api
    build:
      context: ./docker/7.4
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
    image: sail-7.4/app
    ports:
      - "${DOCKER_PORT:-80}:80"
    environment:
      WWWUSER: "${WWWUSER}"
      LARAVEL_SAIL: 1
      XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
      XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
    volumes:
      - ".:/var/www/html"
    network_mode: ${DOCKER_NETWORK}

  db:
    env_file:
      - ./.env
    image: mysql:5.7
    container_name: ${DOCKER_CONTAINER}-db
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: avaliacao
      TZ: America/Sao_Paulo
    network_mode: ${DOCKER_NETWORK}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${DOCKER_CONTAINER}-pma
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=1000M
    ports:
      - ${DOCKER_PMA_PORT}:80
    network_mode: ${DOCKER_NETWORK}

networks:
  avaliacao:
    external: true
volumes:
  dbdata: {}
